spring:
  datasource:
    username: dev
    password: 123456
    url: jdbc:mysql://localhost:3306/mall_oms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000